# Your name and what you do
name: Christopher Chavez
bio: Software Developer

description: Christopher Chavez's Personal Website

# Profile picture
picture: assets/images/profile.jpg

# your url: http://USERNAME.github.io
url: https://doncesarts.github.io

# do you want to display social media links? true or false
social-media: true
# Add your username for the social media websites listed below
# If you don't have an account on any of them, comment out the line
# facebook: myfacebook
#twitter: doncesarts
linkedin: christopher-césar-chávez-lópez-27566b12
github: doncesarts
email: doncesarts@gmail.com
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
# youtube: myyoutube
# spotify: myspotify
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
# medium: medium
# vimeo: myvimeo
# lanyrd: mylanyrd

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# do you want to display an about section? true or false
about: true

# do you want to display a skills section? true or false
skills: true

# add your skills here
skills-list:
    - Languages: JavaScript, Java, HTML, Solidity
    - Web : NodeJs, React, Redux, Jest, Enzyme, Web Design Systems.
    - Web3: Web3.js, Truffle, Ganache, Metamask
    - Databases: Oracle, MySQL, Mongo DB
    - Servers: Apache Tomcat, WebLogic, WebSphere Application Server
    - Frameworks: Struts, JSF, Spring, Spring MVC, Hibernate, JPA


# do you want to display a projects section? true or false
projects: true

# add your projects here
project-list:
    React-Dapp-ERC721-Token:
        name: Decentralized Art Market
        description: Dapp Example of Decentralized ERC721 Tokens Market
        url: https://github.com/doncesarts/react-dapp-erc721-token



# do you want to display the theme attribution? true or false
footer: true

# Enable animations? true or false
animation: true

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
