# Your name and what you do
name: Decentralized Synergy
bio: Research and development for blockchain solutions.

description: Decentralized Synergy Website

# Profile picture
picture: assets/images/profile_.jpg
 
url: https://0xdsynergy.github.io

# do you want to display social media links? true or false
social-media: false
# Add your username for the social media websites listed below
# If you don't have an account on any of them, comment out the line
# facebook: myfacebook
#twitter: 0xdsynergy
# linkedin: christopher-césar-chávez-lópez-27566b12
github: 0xdsynergy
# email: 0xdsynergy@gmail.com
# cv: assets/cv-dapp._pdf
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
# youtube: myyoutube
# spotify: myspotify
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
# medium: medium
# vimeo: myvimeo
# lanyrd: mylanyrd

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: large

# do you want to display an about section? true or false
about: true

# do you want to display a skills section? true or false
skills: true

# add your skills here
skills-list:
    - <b>Automation </b> OpenZepelling Defender 
    - <b>Languages </b> Solidity, Typescript
    - <b>Web </b>  NodeJs, React, Redux, Jest, Enzyme, Web Design Systems, GraphQL.
    - <b>Web3</b>  Web3.js, Ethers Truffle, Hardhat, Ganache, Metamask


# do you want to display a projects section? true or false
projects: true

# add your projects here
project-list:
    mStable-contracts:
        name: mStable
        description: Decentralised Stablecoin Ecosystem
        url: https://github.com/mstable/mStable-contracts
        tags: React, Ethers, Hardhat, Solidity

# do you want to display a badges section? true or false
badges: false

# add your badges here
badge-list:
    Ethereum-Bootcamp-Udemy:
        name: Ethereum Blockchain Developer Bootcamp With Solidity (2021)
        organization: Udemy
        url: https://udemy-certificate.s3.amazonaws.com/image/UC-bfbb4b81-b372-4e47-9043-a155557f1a1a.jpg

# do you want to display a badges section? true or false
contributors: true

# add your badges here
contributor-list:
    doncesarts:
        name: doncesarts.eth
        organization: 0xdsynergy
        url: https://github.com/doncesarts



# do you want to display the theme attribution? true or false
footer: true

# Enable animations? true or false
animation: true

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
